### ISSUE TITLE
Chrome blocks download

### ISSUE THREAD

**Issue by luke-john** [altryne/extensionizr#39]
When attempting to download an extension from chrome I receive the message 

> extensionizr_cus....zip may harm your browsing experience so Chrome has blocked it.

The notice has a learn more option which takes you to the following page.

https://support.google.com/chrome/answer/6261569?p=ib_download_blocked&hl=en&rd=1

I'm assuming the download is falling foul of the following check 

> Adding unwanted extensions or toolbars to your browser

**Comment by altryne** [comment]
Looks like chrome resolved this!
